version: '3.8'

services:
  prysm-beacon-chain:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prysm-beacon-chain
    volumes:
      - ./prysm:/data/prysm
      - ./beacondata:/data/beacondata
    ports:
      - 22315:4000
      - 22316:13000
      - 22317:12000/udp
    networks:
      - eth_network
    command: >
      sh -c "/usr/local/bin/beacon-start.sh"

  eth:
    build:
      context: ./eth
      dockerfile: Dockerfile
    container_name: eth
    volumes:
      - ./prysm/:/data/prysm/:ro
      - ./ethdata:/data/ethdata
    ports:
      - 22311:8545
      - 22312:8546
      - 22313:30303
      - 22314:8551
    networks:
      - eth_network
    command:
      [
        "--mainnet",
        "--syncmode=snap",
        "--datadir=/data/ethdata",
        "--allow-insecure-unlock",
        "--rpc.allow-unprotected-txs",
        "--http",
        "--http.addr=0.0.0.0",
        "--http.port=8545",
        "--http.corsdomain=*",
        "--http.vhosts=*",
        "--http.api=web3,debug,eth,txpool,net,engine",
        "--authrpc.addr=0.0.0.0",
        "--authrpc.vhosts=*",
        "--authrpc.port=8551",
        "--authrpc.jwtsecret=/data/prysm/jwt.hex",
        "--ws",
        "--ws.addr=0.0.0.0",
        "--ws.port=8546",
        "--ws.origins=*",
        "--cache=4096",
        "--ws.api=web3,debug,eth,txpool,net,engine",
        "--maxpeers=300",
        "--port=30303"
      ]
#    command: --cache 4096 --http --http.api web3,eth,net,personal,txpool,engine,admin --http.addr 0.0.0.0 --http.port 8545  --datadir /data/ethdata   --allow-insecure-unlock --rpc.allow-unprotected-txs  --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.vhosts localhost --maxpeers=300 --authrpc.jwtsecret /data/prysm/jwt.hex

networks:
  eth_network:
    driver: bridge
