version: "3.8"

services:
  geth:
    image: ethereum/client-go:latest
    volumes:
      - ./eth:/root/.ethereum
      - ./jwt/jwtsecret:/jwt/jwtsecret

    ports:
      - 8545:8545
      - 30303:30303
      - 8551:8551
    restart: unless-stopped
    networks:
      - eth_network
    command:
      [
        "--mainnet",
        "--syncmode","snap",
        "--datadir=/root/.ethereum",
        "--http",
        "--http.addr", "0.0.0.0",
        "--http.port", "8545",
        "--authrpc.addr", "0.0.0.0",
        "--authrpc.vhosts=0.0.0.0",
        "--authrpc.port", "8551",
        "--http.api", "ersonal,eth,net,web3,debug,txpool,admin",
        "--authrpc.jwtsecret=/jwt/jwtsecret",
        "--cache", "1024",
        "--http.corsdomain", "*",
        "--maxpeers=500",
        "--metrics"
      ]



  beacon-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    volumes:
      - ./eth2:/data
      - ./jwt/jwtsecret:/jwt/jwtsecret

    ports:
      - 4000:4000
      - 13000:13000
      - 12000:12000/udp
    restart: unless-stopped
    networks:
      - eth_network
    command:
      [
        "--datadir=/data",
        "--jwt-secret=/jwt/jwtsecret",
        "--execution-endpoint=http://69.197.168.146:8551", # Enter your private ip for your system
        "--mainnet",
        "--accept-terms-of-use",
        "--rpc-host=0.0.0.0",
        "--grpc-gateway-host=0.0.0.0",
        "--monitoring-host=0.0.0.0"
      ]
networks:
  eth_network:
    driver: bridge