IsTrustedSequencer = false

[Log]
Environment = "production" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 300
SyncOnlyTrusted = true
TrustedSequencerURL = "https://rpc.merlinchain.io" # L2 rpc, for testnet: https://testnet-rpc.merlinchain.io

[Etherman]
URL = "http://18.142.49.94:8545" # L1 rpc, for testnet: http://61.10.9.18:7545
ForkIDChunkSize = 20000
MultiGasProvider = false

[RPC]
Host = "0.0.0.0"
Port = 8123
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 100
SequencerNodeURI = "https://rpc.merlinchain.io" # L2 rpc, for testnet: https://testnet-rpc.merlinchain.io
EnableL2SuggestedGasPricePolling = false
TraceBatchUseHTTPS = true
[RPC.WebSockets]
Enabled = true
Host = "0.0.0.0"
Port = 8133

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "merlin-state-db"
Port = "5432"
EnableLog = false
MaxConns = 800

[Pool]
DefaultMinGasPriceAllowed = 50000000

[Pool.DB]
User = "pool_user"
Password = "pool_password"
Name = "pool_db"
Host = "merlin-pool-db"
Port = "5432"
EnableLog = false
MaxConns = 800

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = true

[MTClient]
URI  = "cdk-validium-prover:50061"

[Executor]
URI = "cdk-validium-prover:50071"
MaxResourceExhaustedAttempts = 5
WaitOnResourceExhaustion = "1s"
MaxGRPCMessageSize = 100000000